// Repositories Actions
export const REPO_INITIALIZATION = "REPO_INITIALIZATION";
export const FETCH_REPOSITORY = "FETCH_REPOSITORY";
export const REPO_NOT_FOUND = "REPO_NOT_FOUND";
export const ADD_REPO_DATA = "ADD_REPO_DATA";
export const REMOVE_REPO = "REMOVE_REPO";
export const HIGHLIGHT_REPO = "HIGHLIGHT_REPO";
export const TOGGLE_REPO_HIGHLIGHT = "TOGGLE_REPO_HIGHLIGHT";
// Autocomplete Actions
export const SEARCH_REPOSITORIES = "SEARCH_REPOSITORIES";
export const UPDATE_SEARCH_TERM = "UPDATE_SEARCH_TERM";
export const ADD_SEARCH_RESULTS = "ADD_SEARCH_RESULTS";
export const RESET_AUTOCOMPLETE = "RESET_AUTOCOMPLETE";
